# Generated by Django 5.0.7 on 2024-07-20 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_excerpt_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=75, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
