# Generated by Django 3.2.25 on 2024-07-19 17:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('content', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category', models.CharField(choices=[('Flags', 'Flags'), ('Events', 'Events'), ('People', 'People')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
