# Generated by Django 5.0.7 on 2024-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='category',
            field=models.CharField(choices=[('Flags', 'Flags'), ('Did you know?', 'Did you know?'), ('People', 'People'), ('Glossary', 'Glossary')], max_length=50),
        ),
    ]
